# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper

from .summarize.client import SummarizeClient, AsyncSummarizeClient


class RecipesClient:
    """This class will handle all the clients for the recipes API"""

    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self.summarize = SummarizeClient(client_wrapper=client_wrapper)
        # TODO: Add more clients here


class AsyncRecipesClient:
    """This class will handle all the clients for the recipes API"""

    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self.summarize = AsyncSummarizeClient(client_wrapper=client_wrapper)
        # TODO: Add more clients here