# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OpenAiCompletionObject(str, enum.Enum):
    COMPLETION = "completion"
    COMPLETION_CHUNK = "completion.chunk"

    def visit(
        self, completion: typing.Callable[[], T_Result], completion_chunk: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is OpenAiCompletionObject.COMPLETION:
            return completion()
        if self is OpenAiCompletionObject.COMPLETION_CHUNK:
            return completion_chunk()
