# This file was auto-generated by Fern from our API Definition.

import typing

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class SummarizeResponse(pydantic.BaseModel):
    summary: typing.Optional[str]